# Ref: https://velog.io/@chickenfondue/nginx-docker-compose%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%A6%AC%EB%B2%84%EC%8A%A4-%ED%94%84%EB%A1%9D%EC%8B%9C-%EA%B5%AC%EC%84%B1

networks:
  server-connection:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.20-perl
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - api
  api:
    container_name: fastapi
    image: bge-m3-fastapi:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build: ./
    restart: always
    expose:
      - '8000'
    networks:
      - server-connection
