name: CD with docker-compose

on:
  push:
    branches: [ "feature/llama-cpp-python" ]
  pull_request:
    branches: [ "feature/llama-cpp-python" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --tag "${{ secrets.DOCKER_REPO }}:latest"
          docker push ${{ secrets.DOCKER_USERNAME }}/bge-m3-fastapi

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} 
        id: deploy
        with: 
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.KEY }}
          envs: DOCKER_REPO
          script: |
            docker rm -f $(docker ps -qa)
            docker pull ${{ secrets.DOCKER_REPO }}:latest
            docker run -d --log-driver=syslog -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}:latest

